:_mod-docs-content-type: PROCEDURE

[id="configuring-openstackshort-for-events-collection-and-transport_{context}"]
= Configuring {OpenStackShort} for events collection and transport

[role="_abstract"]
Write a short introductory paragraph that provides an overview of the module. The introduction should include what the module will help the user do and why it will be beneficial to the user. Include key words that relate to the module to maximize search engine optimization.

.Prerequisites

* A bulleted list of conditions that must be satisfied before the user starts the steps in this module.
* Prerequisites can be full sentences or sentence fragments; however, prerequisite list items must be parallel.

.Procedure

. Make each step an instruction.

. Include one command or action for each step with the exception of simple follow-step, for example:
.. Do this thing and then select *Next*.
.. Do this other thing and then select *Next*.

. Use an unnumbered bullet (*) if the procedure includes only one step.

.Verification

Delete this section if it does not apply to your module. Provide the user with verification methods for the procedure, such as expected output or commands that confirm success or failure.

* Provide an example of expected command output or a pop-up window that the user receives when the procedure is successful.
* List actions for the user to complete, such as entering a command, to determine the success or failure of the procedure.
* Make each step an instruction.
* Include one command or action per step.
* Use an unnumbered bullet (*) if the verification includes only one step.

[role="_additional-resources"]
.Next steps

* This section is optional.
* Provide a bulleted list of links that contain instructions that might be useful to the user after they complete this procedure.
* Use an unnumbered bullet (*) if the list includes only one step.

NOTE: Do not use *Next steps* to provide a second list of instructions.

[role="_additional-resources"]
.Additional resources

* This section is optional.
* Provide a bulleted list of links to other closely-related material. These links can include `link:` and `xref:` macros.
* Use an unnumbered bullet (*) if the list includes only one step.

